controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    io_and_status_controller:
      type: ur_controllers/GPIOController


io_and_status_controller:
  ros__parameters:
    tf_prefix: "$(var tf_prefix)"

joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)joint1
      - $(var tf_prefix)joint2
      - $(var tf_prefix)joint3
      - $(var tf_prefix)joint4
      - $(var tf_prefix)joint5
      - $(var tf_prefix)joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)joint1: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)joint2: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)joint3: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)joint4: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)joint5: { trajectory: 0.2, goal: 0.1 }
      $(var tf_prefix)joint6: { trajectory: 0.2, goal: 0.1 }

